learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('user_login/', views.user_login, name='user_login'),
    path('user_profile/', views.profile_page, name="user_profile"),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfoModel(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfoModel
from django.core import validators



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    username = forms.CharField()

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfoModel
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm, UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("This is a special page")

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basic_app/registration.html',
                            {'user_form': user_form,
                            'profile_form': profile_form,
                            'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Your account is not active")
        else:
            print('someone tried to login and failed')
            return HttpResponse("invalid login details")
    else:
        return render(request, 'basic_app/login.html')

def profile_page(request):
    
    return render(request, "basic_app/profile.html")

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container">

        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a>
        {% if user.is_authenticated %}

        <a class="navbar-link" href="{% url 'logout' %}">Logout</a>
        <a class="navbar-link" href="{%url 'basic_app:user_profile'%}">Profile</a>

        {%else%}

        <a class="navbar-link"href="{% url 'basic_app:user_login' %}">Login</a>

        {% endif %}
      </div>
    </nav>
    {%if user.is_authenticated%}
    <h1>Welcome, {{user.username}}</h1>
    {%endif%}
    {% block body_block %}
    <div class="container">

    </div>
    {% endblock %}
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html"%}
{%block body_block%}

<div class="container">
  <h1>Django level five</h1>
</div>

{%endblock%}

learning_users/templates/basic_app/login.html
{%extends 'basic_app/base.html'%}
{%block body_block%}

<h1>Please log in</h1>
<form action="{% url 'basic_app:user_login'%}" method="post">
  {%csrf_token%}
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="enter username">

  <label for="password">Password:</label>
  <input type="password" name="password">

  <input type="submit" name="" value="Login">
</form>

{%endblock%}

learning_users/templates/basic_app/profile.html
{%extends "basic_app/base.html"%}

{%block body_block%}

<h1>Public profile</h1>

<h3>Username: {{user.username}}</h3>
<img src="{{user.profile_pic.url}}" alt=""></img>

{%endblock%}

learning_users/templates/basic_app/registration.html
{%extends "basic_app/base.html"%}
{%load static%}
{%block body_block%}

<div class="container">
  {%if registered%}
    <h1>thank you for registering</h1>
  {%else%}
    <h1>register here</h1>
    <h3>fill out the form</h3>

    <form method="post" enctype="multipart/form-data">
      {%csrf_token%}
      {{ user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" value="Register">
    </form>
  {%endif%}
</div>

{%endblock%}